# my_complete_config.yaml
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
# external-controller: 127.0.0.1:9090

# Server info for shadowsocks
proxies:
  - name: "MySSServer"
    type: ss
    server: # IP
    port: # port
    cipher: chacha20-ietf-poly1305
    password: # password
    # udp: true

# Groups definition
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - MySSServer

  - name: DEFAULT_POLICY
    type: select
    proxies:
      - DIRECT
      - PROXY

# Rule provider definition
rule-providers:
  proxy_domains:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ErrOzz/ss_conditions/refs/heads/main/clash_proxy_rules.yaml"
    path: ./proxy_domains.yaml # Lockal rule file name
    interval: 3600 # Update time 1 hour

# Rules list
rules:
  - IP-CIDR,10.0.0.0/24,DIRECT
  - IP-CIDR,100.64.0.0/22,DIRECT
  - IP-CIDR,172.16.0.0/20,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-SUFFIX,localhost,DIRECT

  - RULE-SET,proxy_domains,PROXY

  # - GEOIP,RU,DIRECT

  - MATCH,DEFAULT_POLICY
